<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="1" failed="0" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-10-21T13:03:50 IST" name="Suite" finished-at="2022-10-21T13:04:23 IST" duration-ms="33117">
    <groups>
    </groups>
    <test started-at="2022-10-21T13:03:50 IST" name="Test" finished-at="2022-10-21T13:04:23 IST" duration-ms="33117">
      <class name="com.appName.domainName.CreateOrganizationTest">
        <test-method is-config="true" signature="beforeClass1Test()[pri:0, instance:com.appName.domainName.CreateOrganizationTest@57cf54e1]" started-at="2022-10-21T13:03:51 IST" name="beforeClass1Test" finished-at="2022-10-21T13:03:56 IST" duration-ms="5285" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass1Test -->
        <test-method is-config="true" signature="beforeMethod1Test()[pri:0, instance:com.appName.domainName.CreateOrganizationTest@57cf54e1]" started-at="2022-10-21T13:03:56 IST" name="beforeMethod1Test" finished-at="2022-10-21T13:04:01 IST" duration-ms="5409" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod1Test -->
        <test-method signature="testCaseName()[pri:0, instance:com.appName.domainName.CreateOrganizationTest@57cf54e1]" started-at="2022-10-21T13:04:01 IST" name="testCaseName" finished-at="2022-10-21T13:04:20 IST" duration-ms="19051" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCaseName -->
        <test-method is-config="true" signature="afterMethod1Test()[pri:0, instance:com.appName.domainName.CreateOrganizationTest@57cf54e1]" started-at="2022-10-21T13:04:20 IST" name="afterMethod1Test" finished-at="2022-10-21T13:04:23 IST" duration-ms="2890" status="FAIL">
          <exception class="org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException">
            <message>
              <![CDATA[Fail to save: an error occurs while saving the package : Cannot invoke "java.io.OutputStream.write(byte[], int, int)" because "this.os" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : Cannot invoke "java.io.OutputStream.write(byte[], int, int)" because "this.os" is null
at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:554)
at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1505)
at org.apache.poi.ooxml.POIXMLDocument.write(POIXMLDocument.java:242)
at com.orgName.genericUtility.ExcelUtility.saveExcelData(ExcelUtility.java:125)
at com.orgName.genericUtility.BaseClass.afterMethod1Test(BaseClass.java:93)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:700)
at org.testng.internal.TestInvoker.runAfterGroupsConfigurations(TestInvoker.java:676)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:660)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.NullPointerException: Cannot invoke "java.io.OutputStream.write(byte[], int, int)" because "this.os" is null
at org.apache.commons.compress.archivers.zip.StreamCompressor$OutputStreamCompressor.writeOut(StreamCompressor.java:306)
at org.apache.commons.compress.archivers.zip.StreamCompressor.writeCounted(StreamCompressor.java:273)
at org.apache.commons.compress.archivers.zip.StreamCompressor.writeCounted(StreamCompressor.java:269)
at org.apache.commons.compress.archivers.zip.ZipArchiveOutputStream.writeCounted(ZipArchiveOutputStream.java:936)
at org.apache.commons.compress.archivers.zip.ZipArchiveOutputStream.writeLocalFileHeader(ZipArchiveOutputStream.java:1043)
at org.apache.commons.compress.archivers.zip.ZipArchiveOutputStream.putArchiveEntry(ZipArchiveOutputStream.java:787)
at org.apache.commons.compress.archivers.zip.ZipArchiveOutputStream.putArchiveEntry(ZipArchiveOutputStream.java:727)
at org.apache.poi.openxml4j.opc.internal.ZipContentTypeManager.saveImpl(ZipContentTypeManager.java:66)
at org.apache.poi.openxml4j.opc.internal.ContentTypeManager.save(ContentTypeManager.java:452)
at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:520)
... 37 more
]]>
            </full-stacktrace>
          </exception> <!-- org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod1Test -->
        <test-method is-config="true" signature="afterCass1Test()[pri:0, instance:com.appName.domainName.CreateOrganizationTest@57cf54e1]" started-at="2022-10-21T13:04:23 IST" name="afterCass1Test" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1666337663680" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterCass1Test -->
        <test-method is-config="true" signature="aftersuite1Test()[pri:0, instance:com.appName.domainName.CreateOrganizationTest@57cf54e1]" started-at="2022-10-21T13:04:24 IST" name="aftersuite1Test" finished-at="2022-10-21T13:04:24 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftersuite1Test -->
      </class> <!-- com.appName.domainName.CreateOrganizationTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
